/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles;

import vista.componentes.Estilo;

/**
 *
 * @author cielo
 */
public class InformeCargos extends javax.swing.JPanel {

    /**
     * Creates new form InformeCargos
     */
    public InformeCargos() {
        initComponents();
        Estilo.aplicarSubtitulo(lblInfCargos);
        Estilo.aplicarTexto(lblCantCargos);
        Estilo.aplicarTexto(lblPorcentaje);
        Estilo.aplicarSeparadorTitulo(sepTituloForm);
        Estilo.aplicarTextField(txtCantCargos);
        Estilo.aplicarComboBox(cmbPorcentaje);
        Estilo.aplicarBoton(btnAceptar);
        Estilo.aplicarCard(this); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbPorcentaje = new javax.swing.JComboBox<>();
        txtCantCargos = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        lblInfCargos = new javax.swing.JLabel();
        lblCantCargos = new javax.swing.JLabel();
        lblPorcentaje = new javax.swing.JLabel();
        sepTituloForm = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(300, 300));

        txtCantCargos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnAceptar.setText("Aceptar");

        lblInfCargos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblInfCargos.setText("Distribución de cargos a cubrir");
        lblInfCargos.setInheritsPopupMenu(false);

        lblCantCargos.setText("Cantidad de cargos");
        lblCantCargos.setInheritsPopupMenu(false);

        lblPorcentaje.setText("Porcentaje");
        lblPorcentaje.setInheritsPopupMenu(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCantCargos)
                        .addGap(140, 140, 140)
                        .addComponent(lblPorcentaje))
                    .addComponent(sepTituloForm, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCantCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(cmbPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblInfCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblInfCargos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sepTituloForm, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantCargos)
                    .addComponent(lblPorcentaje))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantCargos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAceptar)
                .addContainerGap(352, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JComboBox<String> cmbPorcentaje;
    private javax.swing.JLabel lblCantCargos;
    private javax.swing.JLabel lblInfCargos;
    private javax.swing.JLabel lblPorcentaje;
    private javax.swing.JSeparator sepTituloForm;
    private javax.swing.JTextField txtCantCargos;
    // End of variables declaration//GEN-END:variables
}
