/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.paneles;

import vista.componentes.Estilo;

/**
 *
 * @author cielo
 */
public class InformeDivision extends javax.swing.JPanel {

    /**
     * Creates new form InformeDivision
     */
    public InformeDivision() {
        initComponents();
        Estilo.aplicarTitulo(lblDivision);
        Estilo.aplicarSubtitulo(lblCantVotos);
        Estilo.aplicarSubtitulo(lblNroVotos);
        Estilo.aplicarTabla(tblVotosPartidos);
        Estilo.aplicarTabla(tblVotosCargo);
        Estilo.aplicarCard(this); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblVotosCargo = new javax.swing.JTable();
        lblDivision = new javax.swing.JLabel();
        lblCantVotos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVotosPartidos = new javax.swing.JTable();
        lblNroVotos = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 500));

        tblVotosCargo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Número de orden", "Votos por cargo", "Explicación"
            }
        ));
        jScrollPane2.setViewportView(tblVotosCargo);

        lblDivision.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDivision.setText("División de votos");
        lblDivision.setInheritsPopupMenu(false);

        lblCantVotos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCantVotos.setText("Cantidad de votos");
        lblCantVotos.setInheritsPopupMenu(false);

        tblVotosPartidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Denominación de partido", "Cantidad de votos", "Porcentaje"
            }
        ));
        jScrollPane1.setViewportView(tblVotosPartidos);

        lblNroVotos.setText("jLabel1");
        lblNroVotos.setInheritsPopupMenu(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNroVotos)
                .addGap(118, 118, 118))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblCantVotos, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblDivision, javax.swing.GroupLayout.Alignment.LEADING))
                    .addContainerGap(142, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(lblNroVotos)
                .addGap(70, 70, 70)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(lblDivision)
                    .addGap(18, 18, 18)
                    .addComponent(lblCantVotos)
                    .addContainerGap(198, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCantVotos;
    private javax.swing.JLabel lblDivision;
    private javax.swing.JLabel lblNroVotos;
    private javax.swing.JTable tblVotosCargo;
    private javax.swing.JTable tblVotosPartidos;
    // End of variables declaration//GEN-END:variables
}
