/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author cielo
 */
public class BajaPartido extends javax.swing.JPanel {

    /**
     * Creates new form BajaPartido
     */
    public BajaPartido() {
        initComponents();
        Estilo.aplicarSubtitulo(lblElimine);
        Estilo.aplicarTexto(lblSeleccione);
        Estilo.aplicarSeparadorTitulo(sepTituloForm);
        Estilo.aplicarComboBox(cmbPartidos);
        Estilo.aplicarBoton(btnDarBaja);
        Estilo.aplicarCard(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbPartidos = new javax.swing.JComboBox<>();
        lblSeleccione = new javax.swing.JLabel();
        btnDarBaja = new javax.swing.JButton();
        lblElimine = new javax.swing.JLabel();
        sepTituloForm = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(500, 500));

        lblSeleccione.setText("Seleccione partido a dar de baja");
        lblSeleccione.setInheritsPopupMenu(false);

        btnDarBaja.setText("Dar de baja");

        lblElimine.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblElimine.setText("Elimine un partido del sistema");
        lblElimine.setInheritsPopupMenu(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sepTituloForm, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSeleccione)
                    .addComponent(lblElimine)
                    .addComponent(cmbPartidos, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDarBaja))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblElimine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepTituloForm, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSeleccione)
                .addGap(18, 18, 18)
                .addComponent(cmbPartidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDarBaja)
                .addContainerGap(359, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDarBaja;
    private javax.swing.JComboBox<String> cmbPartidos;
    private javax.swing.JLabel lblElimine;
    private javax.swing.JLabel lblSeleccione;
    private javax.swing.JSeparator sepTituloForm;
    // End of variables declaration//GEN-END:variables
}
